### PR TITLE
Elephant XO

### PR DESCRIPTION
**Pull request by DO97**
5 symbols in a row are needed to win (8x8 grid)

### CODE REVIEW

**Comment by jacklul** [comment]
Is this existing game variant or is it completely made up by you?
The preview image doesn't really fit the grid size, does it?

**Comment by DO97** [comment]
> Is this existing game variant or is it completely made up by you?
> The preview image doesn't really fit the grid size, does it?

I found this game inside another Telegram bot and it's pretty good (obviously, the code is totally based on yours). You can find it already exists on the web, just search for "Tic Tac Toe 8x8".
It takes much more attention than the other versions and it's pretty common to lose by distraction.

I just used the Tic-Tac-Four thumbnail.

**Comment by jacklul** [comment]
You could swap the image with https://i.imgur.com/tv2dmtq.png I just made

**Comment by DO97** [comment]
Swapped (sorry for the double commit)

**Comment by jacklul** [comment]
You can always checkout to earlier commit, re-do (or amend) the edit and then force-push

**Comment by jacklul** [comment]
Now you added two more commits, what you should've done is to checkout https://github.com/jacklul/inlinegamesbot/pull/19/commits/6859965b888390dea7055c8d431d44dafceeb6fb and re-do the change, then force-push so that the commits are deleted

**Comment by DO97** [comment]
Done

**Comment by jacklul** [comment]
Better late merge than never I guess 😇

**Pull request merged**
